In [ ]:
# Importar las librerías requeridas
import numpy as np
import pandas as pd

# Establecer la ruta con los datos de los videojuegos
ruta = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjgWQ8jWpgtMLjkxOfOfRN\
DrHzTNS-dSINU5zcfWZTvkYnU07ezFGlBdkJoWjp805NbecrQmSQrjfR/pub?output=xlsx"
# Leer los datos de los videojuegos.
dataset = pd.read_excel(ruta)

# Obtener la columna solo con los datos de los videojuegos.
dataset = dataset["Nombre"]

In [ ]:
dataset

0                        Elden Ring
1                     Disco Elysium
2          The Witcher 3: Wild Hunt
3         The Last of Us Remastered
4                        God of War
                   ...             
145                         Control
146                 Life is Strange
147                     Titanfall 2
148    Assassin's Creed Brotherhood
149                         Bastion
Name: Nombre, Length: 150, dtype: object

In [ ]:
# Importar las librerías requeridas
import numpy as np
import pandas as pd

# Crear una lista de videojuegos
videojuegos = dataset.shape[0]

# Generar usuarios aleatorios con IDs únicos
num_usuarios = 13
usuarios = ["Usuario_" + str(i) for i in range(num_usuarios)]

# Crear un DataFrame para los votos de los usuarios
data = pd.DataFrame(index=dataset)

# Generar votos aleatorios para los usuarios y agregarlos directamente al DataFrame de data
for usuario in usuarios:
    if usuario == "Usuario_0":
        # Generar un usuario que vote 1 en todos los videojuegos
        data[usuario] = np.random.randint(1, 2, size=videojuegos)
    elif usuario == "Usuario_1":
        # Generar un usuario que vote 2 en todos los videojuegos
        data[usuario] = np.random.randint(2, 3, size=videojuegos)
    elif usuario == "Usuario_2":
        # Generar un usuario que vote 3 en todos los videojuegos
        data[usuario] = np.random.randint(3, 4, size=videojuegos)
    elif usuario == "Usuario_3":
        # Generar un usuario que vote 4 en todos los videojuegos
        data[usuario] = np.random.randint(4, 5, size=videojuegos)
    elif usuario == "Usuario_4":
        # Generar un usuario que vote 5 en todos los videojuegos
        data[usuario] = np.random.randint(5, 6, size=videojuegos)
    elif usuario == "Usuario_5":
        # Generar un usuario que vote entre 1 y 2
        data[usuario] = np.random.randint(1, 3, size=videojuegos)
    elif usuario == "Usuario_6":
        # Generar un usuario que vote entre 2 y 3
        data[usuario] = np.random.randint(2, 4, size=videojuegos)
    elif usuario == "Usuario_7":
        # Generar un usuario que vote entre 3 y 4
        data[usuario] = np.random.randint(3, 5, size=videojuegos)
    elif usuario == "Usuario_8":
        # Generar un usuario que vote entre 4 y 5
        data[usuario] = np.random.randint(4, 6, size=videojuegos)
    else:
        # Generar usuarios que voten en un rango específico entre 1 y 5
        data[usuario] = np.random.randint(1, 6, size=videojuegos)

# Mostrar el DataFrame con los votos
data

Usuario_0  Usuario_1  Usuario_2  Usuario_3  \
Nombre                                                                     
Elden Ring                            1          2          3          4   
Disco Elysium                         1          2          3          4   
The Witcher 3: Wild Hunt              1          2          3          4   
The Last of Us Remastered             1          2          3          4   
God of War                            1          2          3          4   
...                                 ...        ...        ...        ...   
Control                               1          2          3          4   
Life is Strange                       1          2          3          4   
Titanfall 2                           1          2          3          4   
Assassin's Creed Brotherhood          1          2          3          4   
Bastion                               1          2          3          4   

                              Usuario_4  Usuario_5  Usuario_6  Usuario_7  \
Nombre                                                                     
Elden Ring                            5          1          3          3   
Disco Elysium                         5          2          2          4   
The Witcher 3: Wild Hunt              5          2          2          4   
The Last of Us Remastered             5          1          3          4   
God of War                            5          1          3          4   
...                                 ...        ...        ...        ...   
Control                               5          2          3          4   
Life is Strange                       5          1          2          3   
Titanfall 2                           5          2          2          4   
Assassin's Creed Brotherhood          5          1          2          3   
Bastion                               5          2          3          3   

                              Usuario_8  Usuario_9  Usuario_10  Usuario_11  \
Nombre                                                                       
Elden Ring                            5          4           5           3   
Disco Elysium                         5          4           3           1   
The Witcher 3: Wild Hunt              4          1           2           4   
The Last of Us Remastered             4          1           3           2   
God of War                            4          5           2           5   
...                                 ...        ...         ...         ...   
Control                               4          4           2           5   
Life is Strange                       5          5           1           2   
Titanfall 2                           4          1           3           3   
Assassin's Creed Brotherhood          5          1           5           4   
Bastion                               5          1           1           1   

                              Usuario_12  
Nombre                                    
Elden Ring                             3  
Disco Elysium                          3  
The Witcher 3: Wild Hunt               4  
The Last of Us Remastered              4  
God of War                             2  
...                                  ...  
Control                                2  
Life is Strange                        5  
Titanfall 2                            4  
Assassin's Creed Brotherhood           2  
Bastion                                1  

[150 rows x 13 columns]

In [ ]:
# Similitud entre usuarios
import numpy as np
from scipy.spatial.distance import cosine

# Obtener la matriz de votos
votos_matrix = data.to_numpy()

# Calcular la matriz de similitud del coseno manualmente
num_usuarios = votos_matrix.shape[1]
similarity_matrix = np.zeros((num_usuarios, num_usuarios))

for i in range(num_usuarios):
    for j in range(num_usuarios):
        similarity_matrix[i, j] = 1 - cosine(votos_matrix[:, i], votos_matrix[:, j])

print(similarity_matrix)

[[1.         1.         1.         1.         1.         0.94637744
  0.98015394 0.98976876 0.99380849 0.90290988 0.89886428 0.90404866
  0.90231856]
 [1.         1.         1.         1.         1.         0.94637744
  0.98015394 0.98976876 0.99380849 0.90290988 0.89886428 0.90404866
  0.90231856]
 [1.         1.         1.         1.         1.         0.94637744
  0.98015394 0.98976876 0.99380849 0.90290988 0.89886428 0.90404866
  0.90231856]
 [1.         1.         1.         1.         1.         0.94637744
  0.98015394 0.98976876 0.99380849 0.90290988 0.89886428 0.90404866
  0.90231856]
 [1.         1.         1.         1.         1.         0.94637744
  0.98015394 0.98976876 0.99380849 0.90290988 0.89886428 0.90404866
  0.90231856]
 [0.94637744 0.94637744 0.94637744 0.94637744 0.94637744 1.
  0.93583782 0.93387092 0.94307148 0.88106452 0.86606152 0.85608082
  0.83244275]
 [0.98015394 0.98015394 0.98015394 0.98015394 0.98015394 0.93583782
  1.         0.97260599 0.97598272 0.885

In [ ]:
# Similitud entre Juegos
import numpy as np
from scipy.spatial.distance import cosine

# Obtener la matriz de votos
votos_matrix = data.to_numpy()

# Calcular la matriz de similitud del coseno manualmente
num_videojuegos = votos_matrix.shape[0]
similarity_matrix = np.zeros((num_videojuegos, num_videojuegos))

for i in range(num_videojuegos):
    for j in range(num_videojuegos):
        similarity_matrix[i, j] = 1 - cosine(votos_matrix[i, :], votos_matrix[j, :])

print(similarity_matrix)

[[1.         0.98057975 0.89411817 ... 0.94648623 0.94129939 0.96716863]
 [0.98057975 1.         0.90332248 ... 0.95045023 0.95491911 0.96360634]
 [0.89411817 0.90332248 1.         ... 0.84949442 0.91443529 0.9589123 ]
 ...
 [0.94648623 0.95045023 0.84949442 ... 1.         0.97365584 0.94283651]
 [0.94129939 0.95491911 0.91443529 ... 0.97365584 1.         0.97724452]
 [0.96716863 0.96360634 0.9589123  ... 0.94283651 0.97724452 1.        ]]
